services:
  metacubexd:
    container_name: metacubexd
    image: ghcr.io/mofeiss/metacubexd:latest
    restart: always
    ports:
      - '8088:80'
    environment:
      DEFAULT_BACKEND_URL: http://aliyun200m:9090
    volumes:
      - /opt/mihomo:/opt/mihomo

  mihomo:
    container_name: mihomo
    image: docker.io/metacubex/mihomo:latest
    restart: always
    pid: host
    network_mode: host
    cap_add:
      - ALL
    volumes:
      - /opt/mihomo:/root/.config/mihomo
      - /dev/net/tun:/dev/net/tun
